---
- name: Install dev packages
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - gcc
      - python
      - python-devel
      - python-alembic
      - python-psycopg2
      - redhat-rpm-config


- name: Install python packages from requirements.txt
  pip:
      requirements: /vagrant/requirements.txt

- command: python createdb.py
  args:
    chdir: /vagrant/
    creates: /vagrant/alembic.ini
